### ISSUE TITLE
Error with newer version of keras - TF

### ISSUE THREAD

**Issue by dorienh** [brannondorsey/midi-rnn#7]
I probably should downgrade my libraries as you say in the requirements, but I don't want to at this point. 

Is there a way to fix this error: 

```
Traceback (most recent call last):
  File "/rnn_midi/midi-rnn-master/train.py", line 237, in <module>
    main()
  File "/rnn_midi/midi-rnn-master/train.py", line 211, in main
    model, epoch = get_model(args)
  File "/rnn_midi/midi-rnn-master/train.py", line 76, in get_model
    model.add(LSTM(**kwargs))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/sequential.py", line 166, in add
    layer(x)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/layers/recurrent.py", line 500, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/layers/recurrent.py", line 2112, in call
    initial_state=initial_state)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/layers/recurrent.py", line 609, in call
    input_length=timesteps)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2957, in rnn
    maximum_iterations=input_length)
TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'
```

**Comment by dorienh** [comment]
My bad, just needed to update both keras and tensorflow.
